### ISSUE TITLE
May 14 2018(Monday) is returned as Non Business day from workflow. Why?

### ISSUE THREAD

**Issue by pavanrajkn** [jlattimer/CRM-DateTime-Workflow-Utilities#14]
Hi ,

I am using this tool to check if the selected  date is business day or not. But Some how 14th may 2018 is returned as non business day even though it is monday. I also checked my Holiday Schedule calender set in MSCRM , There is no holiday created for the above date. But still why the code is returning the day as non business day? Is the code internally checking for any other default calenders? Please help me resolve this issue. Thanks in Advance!!

Pavan Raj K N
pavanrajkn@gmail.com

**Comment by jlattimer** [comment]
Is the workflow running as the user? What timezone does that user have set in their options?

**Comment by jlattimer** [comment]
Since there is no response I will say that if you happen to be using "Dublin, Edinburgh, Lisbon, London" as the time zone right now it's saving as -1 so if your date doesn't have a time associated with it the conversion thinks it's the previous day due to the date now being 11 PM the previous day.

**Comment by pavanrajkn** [comment]
My bad I was using the wrong calendar. Hence this issue. Was able to resolve this by pointing to the right calendar in my workflow.
