### ISSUE TITLE
Comma in Get Year Number

### ISSUE THREAD

**Issue by IngyK** [jlattimer/CRM-DateTime-Workflow-Utilities#23]
I'm using the Get Year Number, and my years come out as 2,018 instead 2018.  I noticed that last winter this fix was to go in next release but I've downloaded the latest release and this still happens. Is there a way around this?

**Comment by AdamGray77** [comment]
I'm seeing the same, and hoping there's a workaround/fix. Thanks.

**Comment by AdmGra** [comment]
I tried some other tools to get the year and found they all returned a number using the thousand separator specified in my orgs settings. So after some playing around I used the String workflow utilities to remove the comma and it's working perfectly.

**Comment by AdamGra** [comment]
Just discovered that 'Get Formatted Date String' is the action to use then set the format to yyyy - saves the extra step removing the comma using the string workflow tools.
