### ISSUE TITLE
Add Business Days not working

### ISSUE THREAD

**Issue by EivionSW** [jlattimer/CRM-DateTime-Workflow-Utilities#4]
Is there a trick to the "Add Business Days" option?  It does not seem to work properly...we are trying to add 10 business days to a date, but it always gives us 10 actual days instead.

**Comment by jlattimer** [comment]
Shouldn't be a trick. Are you setting a calendar at all? I haven't heard anyone else raise issues. 
Example I set the date to 4/25/2017 and added 10 days and got back 5/9/2017 as it skipped 4/29 & 4/30 as well as 5/6 & 5/7.

**Comment by EivionSW** [comment]
No, we didn’t set a calendar at all…do we have to?

**Comment by jlattimer** [comment]
Only need to set one if if you need it to factor in.

**Comment by AhmadElayyan90** [comment]
Hello,

I created calendar and use it in the workflow but, the plugin doesn't take my calendar.
it excluded the Saturday and Sunday every time, not the holidays that in the calendar. 
is the holidays fixed in the plugin? I don't think. 
please help me.
