### ISSUE TITLE
Blank date/time field

### ISSUE THREAD

**Issue by ArtKarp** [jlattimer/CRM-DateTime-Workflow-Utilities#5]
If you use GetDay with a datetime field that is blank, what is retuned to the workflow?  The docs only say Sunday to Saturday.    When use it to set a Day-of-Week option set, it always picks Monday.  My optionset only has the seven days of the week in their normal order.   

(I really want to set the optionset to blank when there is no date, but that isn't working in CRM. I tried using the {clear} setting, but no luck. )

**Comment by jlattimer** [comment]
Before running this step, add a check condition to see if the field is populated or not. If not, set the option set accordingly and move on.
