### ISSUE TITLE
Set Specific Time

### ISSUE THREAD

**Issue by FrankFenneran** [jlattimer/CRM-DateTime-Workflow-Utilities#6]
Jason,
I was thinking that it would be great to have a function to set a specific time in a workflow.  For example, you are creating a task for a future date and want it to be due on that date at a specific time (say 7:00am). Right now there is no way to specify a number of days from another field and ALSO specify a specific time.
What do you think?
-Frank

**Comment by jlattimer** [comment]
I think I'd implement this as a new "Set Time" step which could be used after using a different Add step.

**Comment by FrankFenneran** [comment]
Thanks Jason,

That was the key I was missing.

-Frank

**Comment by jlattimer** [comment]
Added in next release
