### ISSUE TITLE
Get Year Number

### ISSUE THREAD

**Issue by FrankFenneran** [jlattimer/CRM-DateTime-Workflow-Utilities#7]
Hi Jason,
I've been using the tool with Dynamics 365 online and have seen some wonkiness with the GetYearNumber function.  If I pass it a date/time field, it will sometimes return an invalid year (1001 I think), but if I pass in the current date (via the process execution time), it seems to always work fine.
Have you seen this behavior before?

What I'm attempting is to strip the time off of a date/time field, then add days and use a different time.  For example: A date time field is 7/4/2017 15:00:00 and I want to create a new date of this date plus three days at 07:00.  So I pull th

e month, day and year, then reassemble them with a new time using ToDateTime.  Is there a different way I can accomplish this?

-Frank
![workflowdatetime_example](https://user-images.githubusercontent.com/17053011/28018944-242c19b4-654d-11e7-8bc9-41ec0f9030b2.png)

**Comment by jlattimer** [comment]
Probably the best way
