### ISSUE TITLE
Date Year without comma & Month Text

### ISSUE THREAD

**Issue by NicoleCRM** [jlattimer/CRM-DateTime-Workflow-Utilities#8]
I would really like a way to set text fields with parsed date information. For example, I'm trying to set a name field through a workflow as " Account Name + Month Created + Year Created" " ABC Company March 2016".

I used get Month number which will work if I then write if statements for all 12 months, but I am unable to get the year into a format without the comma.

**Comment by slaplant** [comment]
Same here. I would also benefit from having this feature added in - I'm using CRM 2013. I hope you can implement it in your solutions. And great work on this project by the way, it's very helpful!

**Comment by jlattimer** [comment]
Added in next release
